artifacts_root: artifacts

data_processed:
  root_dir: artifacts/processed_data
  data_file: data/Dataset_articles_NoID.csv
  train_data_file: artifacts/processed_data/train_data.csv
  test_data_file: artifacts/processed_data/test_data.csv

training_model:
  root_dir: artifacts/training
  data_file: artifacts/processed_data/train_data.csv
  save_model_path: artifacts/training/model
  save_tokenizer_path: artifacts/training/tokenizer

evaluation_model:
  root_dir: artifacts/evaluation
  test_file: artifacts/processed_data/test_data.csv
  model_path: artifacts/training/model
  tokenizer_path: artifacts/training/tokenizer
