name: workflow

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"

permissions:
  id-token: write
  contents: read

jobs:
  training-job:
    runs-on: [self-hosted, gpu-runner]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Environment & Pull data & Training Model
        env:
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
          MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
          MLFLOW_TRACKING_REPO: ${{ secrets.MLFLOW_TRACKING_REPO }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          echo "Bắt đầu tạo môi trường ảo và cài đặt thư viện..."
          echo "Xóa môi trường cũ cho sạch..."
          rm -rf venv
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

          echo "Kéo dữ liệu từ AWS S3 thông qua DVC..."
          dvc pull --allow-missing

          echo "Bắt đầu tiến trình Training..."
          python main.py

  deploy-job:
    needs: training-job
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_SSH_KEY }}
          port: 22
          script: |
            echo "Đang truy cập vào thư mục dự án..."
            cd /home/ubuntu/Project_Text_Summary

            echo "Lấy code mới nhất từ nhánh main..."
            git pull origin main

            echo "Xây dựng lại Docker Image..."
            docker build -t my-web-app .

            echo "Dọn dẹp container cũ..."
            docker stop web-container || true
            docker rm web-container || true

            echo "Khởi chạy container mới..."
            # Sửa port thành 80:8000 (Giả định FastAPI chạy port 8000)
            docker run -d \
              --name web-container \
              --restart always \
              -p 80:8000 \
              -e MLFLOW_TRACKING_URI=${{ secrets.MLFLOW_TRACKING_URI }} \
              -e MLFLOW_TRACKING_USERNAME=${{ secrets.MLFLOW_TRACKING_USERNAME }} \
              -e MLFLOW_TRACKING_REPO=${{ secrets.MLFLOW_TRACKING_REPO }} \
              -e MLFLOW_TRACKING_PASSWORD=${{ secrets.MLFLOW_TRACKING_PASSWORD }} \
              my-web-app
